from setuptools import setup, find_packages

setup(name='main',
      version='0.1',
      description='The funniest joke in the world',
      url='localhost',
      author='Alexandre Moreau',
      author_email='test@example.com',
      license='MIT',
      py_modules=["main"],
      packages=find_packages(),
      packages_dir={'': 'src'},
      # include_packages_data=True,
      install_requires=[
          'attrs',
          'click',
          'Flask',
          'flask-cors',
          'importlib-metadata',
          'itsdangerous',
          'Jinja2',
          'MarkupSafe',
          'more-itertools',
          'packaging',
          'paho-mqtt',
          'pluggy',
          'py',
          'pymongo',
          'pyparsing',
          'pytest',
          'six',
          'wcwidth',
          'Werkzeug',
          'zipp',
          'py-healthcheck',
          'flask_login',
          'flask_httpauth',
          'pyjwt',
          'configparser'
      ],
      zip_safe=False)
